/*
 * Copyright (C) 2002 Jeff Dike (jdike@karaya.com)
 * Licensed under the GPL
 */

#include <stdio.h>
#include <stdlib.h>
#include "init.h"

static __initdata const char *config[] = {

"#\n",
"# Automatically generated make config: don't edit\n",
"# Linux kernel version: 2.6.33-vs2.3.0.36.29.1\n",
"# Wed Mar 10 20:29:46 2010\n",
"#\n",
"CONFIG_DEFCONFIG_LIST=\"arch/$ARCH/defconfig\"\n",
"CONFIG_GENERIC_HARDIRQS=y\n",
"CONFIG_UML=y\n",
"CONFIG_MMU=y\n",
"CONFIG_NO_IOMEM=y\n",
"# CONFIG_TRACE_IRQFLAGS_SUPPORT is not set\n",
"CONFIG_LOCKDEP_SUPPORT=y\n",
"# CONFIG_STACKTRACE_SUPPORT is not set\n",
"CONFIG_GENERIC_CALIBRATE_DELAY=y\n",
"CONFIG_GENERIC_BUG=y\n",
"CONFIG_GENERIC_TIME=y\n",
"CONFIG_GENERIC_CLOCKEVENTS=y\n",
"CONFIG_IRQ_RELEASE_METHOD=y\n",
"CONFIG_HZ=100\n",
"\n",
"#\n",
"# UML-specific options\n",
"#\n",
"\n",
"#\n",
"# Host processor type and features\n",
"#\n",
"# CONFIG_M386 is not set\n",
"# CONFIG_M486 is not set\n",
"# CONFIG_M586 is not set\n",
"# CONFIG_M586TSC is not set\n",
"# CONFIG_M586MMX is not set\n",
"# CONFIG_M686 is not set\n",
"# CONFIG_MPENTIUMII is not set\n",
"# CONFIG_MPENTIUMIII is not set\n",
"# CONFIG_MPENTIUMM is not set\n",
"# CONFIG_MPENTIUM4 is not set\n",
"# CONFIG_MK6 is not set\n",
"# CONFIG_MK7 is not set\n",
"CONFIG_MK8=y\n",
"# CONFIG_MCRUSOE is not set\n",
"# CONFIG_MEFFICEON is not set\n",
"# CONFIG_MWINCHIPC6 is not set\n",
"# CONFIG_MWINCHIP3D is not set\n",
"# CONFIG_MGEODEGX1 is not set\n",
"# CONFIG_MGEODE_LX is not set\n",
"# CONFIG_MCYRIXIII is not set\n",
"# CONFIG_MVIAC3_2 is not set\n",
"# CONFIG_MVIAC7 is not set\n",
"# CONFIG_MPSC is not set\n",
"# CONFIG_MCORE2 is not set\n",
"# CONFIG_MATOM is not set\n",
"# CONFIG_GENERIC_CPU is not set\n",
"CONFIG_X86_CPU=y\n",
"CONFIG_X86_INTERNODE_CACHE_SHIFT=6\n",
"# CONFIG_X86_CMPXCHG is not set\n",
"CONFIG_X86_L1_CACHE_SHIFT=6\n",
"CONFIG_X86_WP_WORKS_OK=y\n",
"CONFIG_X86_INTEL_USERCOPY=y\n",
"CONFIG_X86_USE_PPRO_CHECKSUM=y\n",
"CONFIG_X86_TSC=y\n",
"CONFIG_X86_CMOV=y\n",
"CONFIG_X86_MINIMUM_CPU_FAMILY=3\n",
"CONFIG_CPU_SUP_INTEL=y\n",
"CONFIG_CPU_SUP_AMD=y\n",
"CONFIG_CPU_SUP_CENTAUR=y\n",
"CONFIG_UML_X86=y\n",
"CONFIG_64BIT=y\n",
"# CONFIG_X86_32 is not set\n",
"# CONFIG_RWSEM_XCHGADD_ALGORITHM is not set\n",
"CONFIG_RWSEM_GENERIC_SPINLOCK=y\n",
"# CONFIG_ARCH_HAS_SC_SIGNALS is not set\n",
"# CONFIG_ARCH_REUSE_HOST_VSYSCALL_AREA is not set\n",
"CONFIG_SMP_BROKEN=y\n",
"CONFIG_GENERIC_HWEIGHT=y\n",
"# CONFIG_STATIC_LINK is not set\n",
"CONFIG_FLATMEM=y\n",
"CONFIG_FLAT_NODE_MEM_MAP=y\n",
"CONFIG_PAGEFLAGS_EXTENDED=y\n",
"CONFIG_SPLIT_PTLOCK_CPUS=4\n",
"CONFIG_PHYS_ADDR_T_64BIT=y\n",
"CONFIG_ZONE_DMA_FLAG=0\n",
"CONFIG_VIRT_TO_BUS=y\n",
"# CONFIG_KSM is not set\n",
"CONFIG_DEFAULT_MMAP_MIN_ADDR=4096\n",
"# CONFIG_NO_HZ is not set\n",
"# CONFIG_HIGH_RES_TIMERS is not set\n",
"CONFIG_GENERIC_CLOCKEVENTS_BUILD=y\n",
"CONFIG_LD_SCRIPT_DYN=y\n",
"# CONFIG_BINFMT_ELF is not set\n",
"# CONFIG_HAVE_AOUT is not set\n",
"# CONFIG_BINFMT_MISC is not set\n",
"# CONFIG_HOSTFS is not set\n",
"# CONFIG_MCONSOLE is not set\n",
"CONFIG_KERNEL_STACK_ORDER=1\n",
"\n",
"#\n",
"# General setup\n",
"#\n",
"# CONFIG_EXPERIMENTAL is not set\n",
"CONFIG_BROKEN_ON_SMP=y\n",
"CONFIG_INIT_ENV_ARG_LIMIT=128\n",
"CONFIG_LOCALVERSION=\"\"\n",
"# CONFIG_LOCALVERSION_AUTO is not set\n",
"# CONFIG_SWAP is not set\n",
"CONFIG_SYSVIPC=y\n",
"CONFIG_SYSVIPC_SYSCTL=y\n",
"# CONFIG_BSD_PROCESS_ACCT is not set\n",
"\n",
"#\n",
"# RCU Subsystem\n",
"#\n",
"CONFIG_TREE_RCU=y\n",
"# CONFIG_TREE_PREEMPT_RCU is not set\n",
"# CONFIG_TINY_RCU is not set\n",
"# CONFIG_RCU_TRACE is not set\n",
"CONFIG_RCU_FANOUT=64\n",
"# CONFIG_RCU_FANOUT_EXACT is not set\n",
"# CONFIG_TREE_RCU_TRACE is not set\n",
"# CONFIG_IKCONFIG is not set\n",
"CONFIG_LOG_BUF_SHIFT=17\n",
"# CONFIG_CGROUPS is not set\n",
"# CONFIG_SYSFS_DEPRECATED_V2 is not set\n",
"# CONFIG_RELAY is not set\n",
"CONFIG_NAMESPACES=y\n",
"CONFIG_UTS_NS=y\n",
"CONFIG_IPC_NS=y\n",
"CONFIG_USER_NS=y\n",
"# CONFIG_BLK_DEV_INITRD is not set\n",
"# CONFIG_CC_OPTIMIZE_FOR_SIZE is not set\n",
"CONFIG_SYSCTL=y\n",
"CONFIG_ANON_INODES=y\n",
"# CONFIG_EMBEDDED is not set\n",
"CONFIG_UID16=y\n",
"CONFIG_SYSCTL_SYSCALL=y\n",
"CONFIG_KALLSYMS=y\n",
"# CONFIG_KALLSYMS_EXTRA_PASS is not set\n",
"CONFIG_HOTPLUG=y\n",
"CONFIG_PRINTK=y\n",
"CONFIG_BUG=y\n",
"CONFIG_ELF_CORE=y\n",
"CONFIG_BASE_FULL=y\n",
"CONFIG_FUTEX=y\n",
"CONFIG_EPOLL=y\n",
"CONFIG_SIGNALFD=y\n",
"CONFIG_TIMERFD=y\n",
"CONFIG_EVENTFD=y\n",
"CONFIG_SHMEM=y\n",
"CONFIG_AIO=y\n",
"\n",
"#\n",
"# Kernel Performance Events And Counters\n",
"#\n",
"CONFIG_VM_EVENT_COUNTERS=y\n",
"CONFIG_SLUB_DEBUG=y\n",
"# CONFIG_COMPAT_BRK is not set\n",
"# CONFIG_SLAB is not set\n",
"CONFIG_SLUB=y\n",
"# CONFIG_SLOB is not set\n",
"# CONFIG_PROFILING is not set\n",
"\n",
"#\n",
"# GCOV-based kernel profiling\n",
"#\n",
"# CONFIG_SLOW_WORK is not set\n",
"# CONFIG_HAVE_GENERIC_DMA_COHERENT is not set\n",
"CONFIG_SLABINFO=y\n",
"CONFIG_RT_MUTEXES=y\n",
"CONFIG_BASE_SMALL=0\n",
"# CONFIG_MODULES is not set\n",
"CONFIG_BLOCK=y\n",
"# CONFIG_BLK_DEV_BSG is not set\n",
"# CONFIG_BLK_DEV_INTEGRITY is not set\n",
"\n",
"#\n",
"# IO Schedulers\n",
"#\n",
"CONFIG_IOSCHED_NOOP=y\n",
"# CONFIG_IOSCHED_DEADLINE is not set\n",
"# CONFIG_IOSCHED_CFQ is not set\n",
"# CONFIG_DEFAULT_DEADLINE is not set\n",
"# CONFIG_DEFAULT_CFQ is not set\n",
"CONFIG_DEFAULT_NOOP=y\n",
"CONFIG_DEFAULT_IOSCHED=\"noop\"\n",
"# CONFIG_INLINE_SPIN_TRYLOCK is not set\n",
"# CONFIG_INLINE_SPIN_TRYLOCK_BH is not set\n",
"# CONFIG_INLINE_SPIN_LOCK is not set\n",
"# CONFIG_INLINE_SPIN_LOCK_BH is not set\n",
"# CONFIG_INLINE_SPIN_LOCK_IRQ is not set\n",
"# CONFIG_INLINE_SPIN_LOCK_IRQSAVE is not set\n",
"CONFIG_INLINE_SPIN_UNLOCK=y\n",
"# CONFIG_INLINE_SPIN_UNLOCK_BH is not set\n",
"CONFIG_INLINE_SPIN_UNLOCK_IRQ=y\n",
"# CONFIG_INLINE_SPIN_UNLOCK_IRQRESTORE is not set\n",
"# CONFIG_INLINE_READ_TRYLOCK is not set\n",
"# CONFIG_INLINE_READ_LOCK is not set\n",
"# CONFIG_INLINE_READ_LOCK_BH is not set\n",
"# CONFIG_INLINE_READ_LOCK_IRQ is not set\n",
"# CONFIG_INLINE_READ_LOCK_IRQSAVE is not set\n",
"CONFIG_INLINE_READ_UNLOCK=y\n",
"# CONFIG_INLINE_READ_UNLOCK_BH is not set\n",
"CONFIG_INLINE_READ_UNLOCK_IRQ=y\n",
"# CONFIG_INLINE_READ_UNLOCK_IRQRESTORE is not set\n",
"# CONFIG_INLINE_WRITE_TRYLOCK is not set\n",
"# CONFIG_INLINE_WRITE_LOCK is not set\n",
"# CONFIG_INLINE_WRITE_LOCK_BH is not set\n",
"# CONFIG_INLINE_WRITE_LOCK_IRQ is not set\n",
"# CONFIG_INLINE_WRITE_LOCK_IRQSAVE is not set\n",
"CONFIG_INLINE_WRITE_UNLOCK=y\n",
"# CONFIG_INLINE_WRITE_UNLOCK_BH is not set\n",
"CONFIG_INLINE_WRITE_UNLOCK_IRQ=y\n",
"# CONFIG_INLINE_WRITE_UNLOCK_IRQRESTORE is not set\n",
"# CONFIG_MUTEX_SPIN_ON_OWNER is not set\n",
"# CONFIG_FREEZER is not set\n",
"# CONFIG_BLK_DEV is not set\n",
"\n",
"#\n",
"# Character Devices\n",
"#\n",
"# CONFIG_STDERR_CONSOLE is not set\n",
"CONFIG_STDIO_CONSOLE=y\n",
"# CONFIG_SSL is not set\n",
"# CONFIG_NULL_CHAN is not set\n",
"# CONFIG_PORT_CHAN is not set\n",
"# CONFIG_PTY_CHAN is not set\n",
"# CONFIG_TTY_CHAN is not set\n",
"# CONFIG_XTERM_CHAN is not set\n",
"CONFIG_NOCONFIG_CHAN=y\n",
"CONFIG_CON_ZERO_CHAN=\"fd:0,fd:1\"\n",
"CONFIG_CON_CHAN=\"xterm\"\n",
"CONFIG_SSL_CHAN=\"pty\"\n",
"# CONFIG_UNIX98_PTYS is not set\n",
"# CONFIG_LEGACY_PTYS is not set\n",
"# CONFIG_RAW_DRIVER is not set\n",
"# CONFIG_WATCHDOG is not set\n",
"# CONFIG_UML_SOUND is not set\n",
"# CONFIG_SOUND is not set\n",
"# CONFIG_SOUND_OSS_CORE is not set\n",
"# CONFIG_HOSTAUDIO is not set\n",
"# CONFIG_HW_RANDOM is not set\n",
"# CONFIG_UML_RANDOM is not set\n",
"# CONFIG_MMAPPER is not set\n",
"\n",
"#\n",
"# Generic Driver Options\n",
"#\n",
"CONFIG_UEVENT_HELPER_PATH=\"/sbin/hotplug\"\n",
"CONFIG_STANDALONE=y\n",
"# CONFIG_PREVENT_FIRMWARE_BUILD is not set\n",
"CONFIG_FW_LOADER=y\n",
"# CONFIG_FIRMWARE_IN_KERNEL is not set\n",
"CONFIG_EXTRA_FIRMWARE=\"\"\n",
"# CONFIG_SYS_HYPERVISOR is not set\n",
"# CONFIG_NET is not set\n",
"\n",
"#\n",
"# File systems\n",
"#\n",
"# CONFIG_EXT2_FS is not set\n",
"# CONFIG_EXT3_FS is not set\n",
"# CONFIG_EXT4_FS is not set\n",
"# CONFIG_REISERFS_FS is not set\n",
"# CONFIG_JFS_FS is not set\n",
"# CONFIG_FS_POSIX_ACL is not set\n",
"# CONFIG_XFS_FS is not set\n",
"CONFIG_FILE_LOCKING=y\n",
"# CONFIG_FSNOTIFY is not set\n",
"# CONFIG_DNOTIFY is not set\n",
"# CONFIG_INOTIFY is not set\n",
"# CONFIG_INOTIFY_USER is not set\n",
"# CONFIG_QUOTA is not set\n",
"# CONFIG_AUTOFS_FS is not set\n",
"# CONFIG_AUTOFS4_FS is not set\n",
"# CONFIG_FUSE_FS is not set\n",
"\n",
"#\n",
"# Caches\n",
"#\n",
"\n",
"#\n",
"# CD-ROM/DVD Filesystems\n",
"#\n",
"# CONFIG_ISO9660_FS is not set\n",
"# CONFIG_UDF_FS is not set\n",
"\n",
"#\n",
"# DOS/FAT/NT Filesystems\n",
"#\n",
"# CONFIG_MSDOS_FS is not set\n",
"# CONFIG_VFAT_FS is not set\n",
"# CONFIG_NTFS_FS is not set\n",
"\n",
"#\n",
"# Pseudo filesystems\n",
"#\n",
"CONFIG_PROC_FS=y\n",
"# CONFIG_PROC_KCORE is not set\n",
"CONFIG_PROC_SYSCTL=y\n",
"CONFIG_PROC_PAGE_MONITOR=y\n",
"CONFIG_SYSFS=y\n",
"# CONFIG_TMPFS is not set\n",
"# CONFIG_HUGETLB_PAGE is not set\n",
"# CONFIG_CONFIGFS_FS is not set\n",
"# CONFIG_MISC_FILESYSTEMS is not set\n",
"\n",
"#\n",
"# Partition Types\n",
"#\n",
"# CONFIG_PARTITION_ADVANCED is not set\n",
"CONFIG_MSDOS_PARTITION=y\n",
"# CONFIG_NLS is not set\n",
"\n",
"#\n",
"# Linux VServer\n",
"#\n",
"# CONFIG_VSERVER_AUTO_LBACK is not set\n",
"# CONFIG_VSERVER_COWBL is not set\n",
"# CONFIG_VSERVER_PROC_SECURE is not set\n",
"# CONFIG_VSERVER_HARDCPU is not set\n",
"# CONFIG_TAGGING_NONE is not set\n",
"# CONFIG_TAGGING_UID16 is not set\n",
"# CONFIG_TAGGING_GID16 is not set\n",
"CONFIG_TAGGING_ID24=y\n",
"# CONFIG_TAGGING_INTERN is not set\n",
"# CONFIG_TAG_NFSD is not set\n",
"# CONFIG_VSERVER_PRIVACY is not set\n",
"CONFIG_VSERVER_CONTEXTS=768\n",
"# CONFIG_VSERVER_WARN is not set\n",
"# CONFIG_VSERVER_DEBUG is not set\n",
"CONFIG_VSERVER=y\n",
"\n",
"#\n",
"# Security options\n",
"#\n",
"# CONFIG_KEYS is not set\n",
"# CONFIG_SECURITY is not set\n",
"# CONFIG_SECURITYFS is not set\n",
"# CONFIG_DEFAULT_SECURITY_SELINUX is not set\n",
"# CONFIG_DEFAULT_SECURITY_SMACK is not set\n",
"# CONFIG_DEFAULT_SECURITY_TOMOYO is not set\n",
"CONFIG_DEFAULT_SECURITY_DAC=y\n",
"CONFIG_DEFAULT_SECURITY=\"\"\n",
"# CONFIG_CRYPTO is not set\n",
"# CONFIG_BINARY_PRINTF is not set\n",
"\n",
"#\n",
"# Library routines\n",
"#\n",
"CONFIG_GENERIC_FIND_FIRST_BIT=y\n",
"CONFIG_GENERIC_FIND_NEXT_BIT=y\n",
"CONFIG_GENERIC_FIND_LAST_BIT=y\n",
"# CONFIG_CRC_CCITT is not set\n",
"# CONFIG_CRC16 is not set\n",
"# CONFIG_CRC_T10DIF is not set\n",
"# CONFIG_CRC_ITU_T is not set\n",
"# CONFIG_CRC32 is not set\n",
"# CONFIG_CRC7 is not set\n",
"# CONFIG_LIBCRC32C is not set\n",
"CONFIG_HAS_DMA=y\n",
"\n",
"#\n",
"# SCSI device support\n",
"#\n",
"# CONFIG_RAID_ATTRS is not set\n",
"# CONFIG_SCSI is not set\n",
"# CONFIG_SCSI_DMA is not set\n",
"# CONFIG_SCSI_NETLINK is not set\n",
"# CONFIG_MD is not set\n",
"# CONFIG_NEW_LEDS is not set\n",
"# CONFIG_INPUT is not set\n",
"\n",
"#\n",
"# Kernel hacking\n",
"#\n",
"# CONFIG_PRINTK_TIME is not set\n",
"# CONFIG_ENABLE_WARN_DEPRECATED is not set\n",
"# CONFIG_ENABLE_MUST_CHECK is not set\n",
"CONFIG_FRAME_WARN=2048\n",
"# CONFIG_STRIP_ASM_SYMS is not set\n",
"# CONFIG_UNUSED_SYMBOLS is not set\n",
"# CONFIG_DEBUG_FS is not set\n",
"# CONFIG_DEBUG_KERNEL is not set\n",
"# CONFIG_SLUB_DEBUG_ON is not set\n",
"# CONFIG_SLUB_STATS is not set\n",
"CONFIG_DEBUG_BUGVERBOSE=y\n",
"CONFIG_DEBUG_MEMORY_INIT=y\n",
"# CONFIG_RCU_CPU_STALL_DETECTOR is not set\n",
"# CONFIG_SYSCTL_SYSCALL_CHECK is not set\n",
"# CONFIG_SAMPLES is not set\n",
"# CONFIG_DEBUG_STACK_USAGE is not set\n",
""
};

static int __init print_config(char *line, int *add)
{
	int i;
	for (i = 0; i < sizeof(config)/sizeof(config[0]); i++)
		printf("%s", config[i]);
	exit(0);
}

__uml_setup("--showconfig", print_config,
"--showconfig\n"
"    Prints the config file that this UML binary was generated from.\n\n"
);

